### PR TITLE
I improved noninteractive test. Thanks!

### PR DESCRIPTION
**Pull request by rubikitch**

### CODE REVIEW

**Comment by rocky** [comment]
I like what's being done. What's up with the the travis ci failure `test-simple.el:354:31:Error: Wrong type argument: integer-or-marker-p, test-simple-runner-key`?

**Comment by rubikitch** [comment]
It is because I use lexical-binding, which is supported after Emacs24.
CI failed because of testing in Emacs23.
Do you have a wish to support older emacsen?
Then I fix this error.

**Comment by rocky** [comment]
> CI failed because of testing in Emacs23.

Hmm... I use Emacs24 and greater. The packages I've written that use _test-simple_ also assume Emacs24. 

So to be simple we could assume Emacs24 and when someone needs this for Emacs23, _they_ can do the additional work. But I leave which way to go up to you, so what do _you_ think? 

As for Travis, here are the lines I have in the [emacs-dbgr](https://github.com/rocky/emacs-dbgr) that tell it to use Emacs 24:

```
env:
  - EMACS=emacs24

install:
  - if [ "$EMACS" = 'emacs24' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get -qq update &&
      sudo apt-get -qq -f install &&
      sudo apt-get -qq install emacs24 emacs24-el;
    fi
```

**Comment by rubikitch** [comment]
It is about to feature freeze for Emacs 25.1,
and lexical-binding is standard way for now.
Actually many packages require Emacs 24 now.
Emacs 23 is too old, I think.

**Comment by rocky** [comment]
> Emacs 23 is too old, I think.

Ok. So I guess we leave out Emacs 23. Would you make the changes to travis? Thanks.

**Comment by rubikitch** [comment]
Sure!

**Comment by rocky** [comment]
Thanks!

**Pull request merged**
